[package]
name = "niri-alacritty-recent-cwd"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Script to get CWD of most recently focused Alacritty window, in niri"
repository = "https://github.com/khollbach/niri-alacritty-recent-cwd"

[dependencies]
anyhow = "1.0.104"
niri-ipc = "26.4.0"
